/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
  webpack: (config, { isServer }) => {
    // Handle Node.js modules in browser environment
    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
        net: false,
        tls: false,
        crypto: false,
        stream: false,
        url: false,
        zlib: false,
        http: false,
        https: false,
        assert: false,
        os: false,
        path: false,
        "node:crypto": false,
        child_process: false,
        "node:child_process": false,
        "node:fs": false,
        "node:path": false,
        "node:os": false,
        "node:util": false,
        "node:buffer": false,
        "node:stream": false,
        "node:events": false,
        "node:process": false,
        "node:url": false,
        "node:querystring": false,
        "node:http": false,
        "node:https": false,
        "node:zlib": false,
        "node:net": false,
        "node:tls": false,
        "node:dns": false,
        "node:readline": false,
        "node:cluster": false,
        "node:worker_threads": false,
        "node:perf_hooks": false,
        "node:async_hooks": false,
        "node:timers": false,
        "node:util": false,
        "node:vm": false,
        "node:inspector": false,
        "node:trace_events": false,
        "node:fs/promises": false,
        "node:path/posix": false,
        "node:path/win32": false,
        "node:os": false,
        "node:constants": false,
        "node:assert": false,
        "node:assert/strict": false,
        "node:buffer": false,
        "node:console": false,
        "node:process": false,
        "node:punycode": false,
        "node:querystring": false,
        "node:string_decoder": false,
        "node:sys": false,
        "node:timers": false,
        "node:timers/promises": false,
        "node:tty": false,
        "node:util": false,
        "node:v8": false,
        "node:vm": false,
        "node:worker_threads": false,
        "node:zlib": false,
      };
    }
    return config;
  },
};

export default nextConfig;
